version: '3.7'

services:
  # MongoDB Database
  mongo:
    image: mongo:7.0
    container_name: mern-mongo-dev
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data_dev:/data/db
    environment:
      - MONGO_INITDB_DATABASE=mern-app

  # Backend API (Development)
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: mern-backend-dev
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongo:27017/mern-app
    depends_on:
      - mongo
    volumes:
      - ./backend:/app
      - /app/node_modules

  # Frontend React App (Development)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: mern-frontend-dev
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  mongo_data_dev:
